"""empty message

Revision ID: 3c8d78a6b285
Revises: da9610a71bea
Create Date: 2016-11-23 19:59:05.630093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8d78a6b285'
down_revision = 'da9610a71bea'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('is_student_in_class', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'is_student_in_class')
    ### end Alembic commands ###
