"""empty message

Revision ID: 73fdba96cb32
Revises: 0030cb2c004d
Create Date: 2016-11-22 10:29:55.856026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fdba96cb32'
down_revision = '0030cb2c004d'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('class_start_time', sa.DateTime(), nullable=True),
    sa.Column('class_end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class')
    ### end Alembic commands ###
